export const products = [
    {
      id: 1,
      title: "Puma Walking Shoes",
      description: "Designed to ease your daily walking session",
      price: "2500",
      img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375455/01/sv01/fnd/IND/fmt/png/PUMA-Knit-Slip-On--Men's-Walking--Shoes",
      quantity: 1,
    },
    {
      id: 2,
      title: "Canon EOS M50 Mark ",
      description: " Mirrorless Camera(Black)",
      price: "56999",
      img: "https://rukminim1.flixcart.com/image/416/416/knyxqq80/dslr-camera/r/y/x/digital-camera-eos-m50-mark-ii-eos-m50-mark-ii-canon-original-imag2gzkexzqhyhu.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 3,
      title: "ADIDAS ",
      description: "Running Shoes For Men (Grey)",
      price: "3500",
      img: "https://rukminim1.flixcart.com/image/832/832/xif0q/shoe/b/w/r/-original-imagk9fvdyabegmh.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 4,
      title: "APPLE iPhone 12 (Blue, 64 GB)",
      description: " Dual-camera System ",
      price: "50999",
      img: "https://rukminim1.flixcart.com/image/416/416/kg8avm80/mobile/y/7/n/apple-iphone-12-dummyapplefsn-original-imafwg8dpyjvgg3j.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 5,
      title: "Veirdo ",
      description: "Men Printed Round Neck Multicolor T-Shirt",
      price: "599",
      img: "https://rukminim1.flixcart.com/image/832/832/xif0q/t-shirt/y/w/b/s-101-fs-msct-blk-veirdo-original-imagjmmkagpzfsef.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 6,
      title: "Redmi 9",
      description: "black in color",
      price: "3500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Samsung S21",
      description: "black in color",
      price: "20500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    
  ];